one = input("Noun: ")
two = input("Noun: ")
three = input("Plural noun: ")
four = input("Adjective: ")
five = input("Adjective: ")
six = input("Adjective: ")
seven = input("Noun: ")
eight = input("Adverb: ")
nine = input("Plural noun: ")
ten = input("Adjective: ")
eleven = input("Adjective: ")
twelve = input("Part of the body (plural): ")
thirteen = input("Plural noun: ")
fourteen = input("Part of the body (plural): ")
fifteen = input("Part of the body (plural): ")
sixteen = input("Plural noun: ")
seventeen = input("Noun: ")
eighteen = input("Part of the body (plural): ")

print(f"Our dining {one} used to be a war {two}.")
print(f"I thought the battles about correct table {three} would never end.")
print(f"It was us kids versus Mom, and it seemed like a fight that would last to the {four} end.")
print(f"But tonight Dad finally declared a/an {five} truce, and we negotiated a/an {six} peace {seven}.")
print(f"Mom promised to no longer get {eight} upset and shoot us dirty {nine} and make {ten} remarks when we do {eleven} things she doesn't like.")
print(f"We in turn agreed to:")
print(f"1) Use napkins to wipe our {twelve} and not our {thirteen}.")
print(f"2) Keep our {fourteen} off the table.")
print(f"3) Not use our {fifteen} to pick upn {sixteen} from our plates - except for sandwiches or pieces of {seventeen}.")
print(f"4) Never talk with food in our {eighteen}.")