one = input("Noun: ")
two = input("Noun: ")
three = input("Plural noun: ")
four = input("Adjective: ")
five = input("Adjective: ")
six = input("Adjective: ")
seven = input("Noun: ")
eight = input("Adverb: ")
nine = input("Plural noun: ")
ten = input("Adjective: ")
eleven = input("Adjective: ")
twelve = input("Part of the body (plural): ")
thirteen = input("Plural noun: ")
fourteen = input("Part of the body (plural): ")
fifteen = input("Part of the body (plural): ")
sixteen = input("Plural noun: ")
seventeen = input("Noun: ")
eighteen = input("Part of the body (plural): ")

print(f"Our dining {one} used to be a war {two}. ")